# Generated by Django 3.2.6 on 2023-03-01 14:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(auto_created=True, default=uuid.uuid4)),
                ('amount', models.CharField(default=299, max_length=9999)),
                ('token', models.CharField(default='BTC', max_length=9999)),
                ('plan', models.CharField(default='S', max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=6248)),
                ('revenue', models.IntegerField(default=431594)),
            ],
        ),
        migrations.CreateModel(
            name='variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USDT', models.CharField(default='usdt_address', max_length=9999)),
                ('BTC', models.CharField(default='btc_address', max_length=9999)),
                ('ETH', models.CharField(default='eth_address', max_length=9999)),
            ],
        ),
    ]
