# Generated by Django 3.2.6 on 2022-11-28 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20221128_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
