# Generated by Django 3.2.6 on 2022-12-06 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20221206_0334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='balance',
        ),
        migrations.AddField(
            model_name='deposit',
            name='amount',
            field=models.CharField(default=0, max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='deposit',
            name='plan',
            field=models.CharField(default='S', max_length=9999),
        ),
        migrations.AddField(
            model_name='deposit',
            name='token',
            field=models.CharField(default='BTC', max_length=9999),
        ),
    ]
