# Generated by Django 3.2.6 on 2022-12-16 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20221216_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='customer',
        ),
    ]
